### ISSUE TITLE
reproducibility in LIBERO

### ISSUE THREAD

**Issue by arashakb** [moojink/openvla-oft#128]
Hi all, I have tried to evaluate the original LIBERO checkpoints on H100s, but I am getting poor results.

<img width="420" height="245" alt="Image" src="https://github.com/user-attachments/assets/ebe8473e-d15f-41bc-8b79-2e000854f855" />

Any idea on why is this happening? 
I am using the correct transformers and pytorch version. I have set a new conda env for the repo. It is mentioned in the repo that we might get slightly different results if we evaluate on a different GPU. However, here the discrepancy is a lot.

**Comment by arashakb** [comment]
Has anyone been able to reproduce the results in the paper? I have also run the evaluation of the presented checkpoints on A100 40GB and I am almost getting the same results as H100s. So I don't think it's related to the GPU setup at this point

**Comment by itsmehere** [comment]
I am also having issues re-producing LIBERO results, but my problem is likely to do with compute. Did increasing the number of GPUs here: `torchrun --standalone --nnodes 1 --nproc-per-node X vla-scripts/finetune.py \` work for you without any changes? I'm running on A6000s, but training only works if I use `--nproc-per-node 1`. It doesn't work for more than 1 gpu, and training just hangs at the `dist.barrier()` call in finetune.py. Did you face any issues with respect to multi-gpu training?

**Comment by bkk9r4vny2-jpg** [comment]
Hi, @arashakb may I know what's your mujoco version?

**Comment by arashakb** [comment]
> I am also having issues re-producing LIBERO results, but my problem is likely to do with compute. Did increasing the number of GPUs here: `torchrun --standalone --nnodes 1 --nproc-per-node X vla-scripts/finetune.py \` work for you without any changes? I'm running on A6000s, but training only works if I use `--nproc-per-node 1`. It doesn't work for more than 1 gpu, and training just hangs at the `dist.barrier()` call in finetune.py. Did you face any issues with respect to multi-gpu training?

Hi, no that works fine. your problem is something related to your GPU set up that is preventing them from running distributed training (fsdp). The fine tuning code works fine (I have tested on 8 H100s, A100s, A6000s)

**Comment by arashakb** [comment]
> Hi, [@arashakb](https://github.com/arashakb) may I know what's your mujoco version?

Sure. it's 3.3.3

**Comment by bkk9r4vny2-jpg** [comment]
@arashakb Just try running `pip install mujoco==3.3.2`. MuJoCo 3.3.3 renders the floor color a bit differently from the training data, which can hurt performance.

**Comment by csguoh** [comment]
I have the same problem, the reproduced results on LIBERO-Spatial is also exact 56.6% as reported by @arashakb . I have tried installing mujoco==3.32 as suggested but the results are still bad (58.0%). 
FYI, I follow the instruction in [LIBERO](https://github.com/moojink/openvla-oft/blob/main/LIBERO.md#launching-libero-evaluations).md, where I download the HF's pretrained model and run the evaluation code without changing any part. 
I use one H100 for evaluation and my conda env is as follows:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.3.1                    pypi_0    pypi
accelerate                1.10.1                   pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.11.0                   pypi_0    pypi
array-record              0.8.1                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrs                     25.4.0                   pypi_0    pypi
bddl                      3.6.0                    pypi_0    pypi
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2025.9.9             h06a4308_0  
cachetools                6.2.1                    pypi_0    pypi
certifi                   2025.10.5                pypi_0    pypi
charset-normalizer        3.4.4                    pypi_0    pypi
click                     8.3.0                    pypi_0    pypi
cloudpickle               3.1.1                    pypi_0    pypi
contourpy                 1.3.2                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
diffusers                 0.30.3                   pypi_0    pypi
dlimp                     0.0.1                    pypi_0    pypi
dm-tree                   0.1.9                    pypi_0    pypi
draccus                   0.8.0                    pypi_0    pypi
easydict                  1.13                     pypi_0    pypi
einops                    0.8.1                    pypi_0    pypi
etils                     1.13.0                   pypi_0    pypi
evdev                     1.9.2                    pypi_0    pypi
exceptiongroup            1.3.0                    pypi_0    pypi
expat                     2.7.1                h6a678d5_0  
fastapi                   0.119.1                  pypi_0    pypi
fastjsonschema            2.21.2                   pypi_0    pypi
filelock                  3.20.0                   pypi_0    pypi
flatbuffers               25.9.23                  pypi_0    pypi
fonttools                 4.60.1                   pypi_0    pypi
fsspec                    2025.9.0                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
gast                      0.6.0                    pypi_0    pypi
gitdb                     4.0.12                   pypi_0    pypi
gitpython                 3.1.45                   pypi_0    pypi
glfw                      2.10.0                   pypi_0    pypi
google-auth               2.41.1                   pypi_0    pypi
google-auth-oauthlib      1.2.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.75.1                   pypi_0    pypi
gym                       0.26.2                   pypi_0    pypi
gym-notices               0.1.0                    pypi_0    pypi
h11                       0.16.0                   pypi_0    pypi
h5py                      3.15.1                   pypi_0    pypi
hf-xet                    1.1.10                   pypi_0    pypi
huggingface-hub           0.35.3                   pypi_0    pypi
idna                      3.11                     pypi_0    pypi
imageio                   2.37.0                   pypi_0    pypi
imageio-ffmpeg            0.6.0                    pypi_0    pypi
importlib-metadata        8.7.0                    pypi_0    pypi
importlib-resources       6.5.2                    pypi_0    pypi
iniconfig                 2.3.0                    pypi_0    pypi
jinja2                    3.1.6                    pypi_0    pypi
joblib                    1.5.2                    pypi_0    pypi
json-numpy                2.1.1                    pypi_0    pypi
jsonlines                 4.0.0                    pypi_0    pypi
jsonschema                4.25.1                   pypi_0    pypi
jsonschema-specifications 2025.9.1                 pypi_0    pypi
jupyter-core              5.9.1                    pypi_0    pypi
jupytext                  1.18.1                   pypi_0    pypi
keras                     2.15.0                   pypi_0    pypi
kiwisolver                1.4.9                    pypi_0    pypi
ld_impl_linux-64          2.44                 h153f514_2  
libclang                  18.1.1                   pypi_0    pypi
libero                    0.1.0                    pypi_0    pypi
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
libxcb                    1.17.0               h9b100fa_0  
libzlib                   1.3.1                hb25bd0a_0  
llvmlite                  0.45.1                   pypi_0    pypi
markdown                  3.9                      pypi_0    pypi
markdown-it-py            4.0.0                    pypi_0    pypi
markupsafe                3.0.3                    pypi_0    pypi
matplotlib                3.10.7                   pypi_0    pypi
mdit-py-plugins           0.5.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mergedeep                 1.3.4                    pypi_0    pypi
ml-dtypes                 0.2.0                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
mujoco                    3.3.2                    pypi_0    pypi
mypy-extensions           1.1.0                    pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.5                  h7934f7d_0  
networkx                  3.4.2                    pypi_0    pypi
nltk                      3.9.2                    pypi_0    pypi
numba                     0.62.1                   pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-cufile-cu12        1.13.1.3                 pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-cusparselt-cu12    0.7.1                    pypi_0    pypi
nvidia-nccl-cu12          2.19.3                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.8.93                  pypi_0    pypi
nvidia-nvshmem-cu12       3.3.20                   pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
oauthlib                  3.3.1                    pypi_0    pypi
opencv-python             4.12.0.88                pypi_0    pypi
openexr                   3.4.2                    pypi_0    pypi
openssl                   3.0.18               hd6dcaed_0  
openvla-oft               0.0.1                    pypi_0    pypi
opt-einsum                3.4.0                    pypi_0    pypi
packaging                 25.0                     pypi_0    pypi
peft                      0.11.1                   pypi_0    pypi
pillow                    12.0.0                   pypi_0    pypi
pip                       25.2               pyhc872135_1  
platformdirs              4.5.0                    pypi_0    pypi
pluggy                    1.6.0                    pypi_0    pypi
promise                   2.3                      pypi_0    pypi
protobuf                  4.21.12                  pypi_0    pypi
psutil                    7.1.1                    pypi_0    pypi
pthread-stubs             0.3                  h0ce48e5_1  
pyasn1                    0.6.1                    pypi_0    pypi
pyasn1-modules            0.4.2                    pypi_0    pypi
pydantic                  2.12.3                   pypi_0    pypi
pydantic-core             2.41.4                   pypi_0    pypi
pygments                  2.19.2                   pypi_0    pypi
pynput                    1.8.1                    pypi_0    pypi
pyopengl                  3.1.10                   pypi_0    pypi
pyparsing                 3.2.5                    pypi_0    pypi
pytest                    8.4.2                    pypi_0    pypi
python                    3.10.18              h1a3bd86_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-xlib               0.33                     pypi_0    pypi
pyyaml                    6.0.3                    pypi_0    pypi
pyyaml-include            1.4.1                    pypi_0    pypi
readline                  8.3                  hc2a1206_0  
referencing               0.37.0                   pypi_0    pypi
regex                     2025.9.18                pypi_0    pypi
requests                  2.32.5                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
rich                      14.2.0                   pypi_0    pypi
robosuite                 1.4.1                    pypi_0    pypi
rpds-py                   0.28.0                   pypi_0    pypi
rsa                       4.9.1                    pypi_0    pypi
safetensors               0.6.2                    pypi_0    pypi
scipy                     1.15.3                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
sentry-sdk                2.42.0                   pypi_0    pypi
setuptools                80.9.0                   pypi_0    pypi
six                       1.17.0                   pypi_0    pypi
smmap                     5.0.2                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sqlite                    3.50.2               hb25bd0a_1  
starlette                 0.48.0                   pypi_0    pypi
sympy                     1.14.0                   pypi_0    pypi
tensorboard               2.15.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorflow                2.15.0                   pypi_0    pypi
tensorflow-addons         0.23.0                   pypi_0    pypi
tensorflow-datasets       4.9.3                    pypi_0    pypi
tensorflow-estimator      2.15.0                   pypi_0    pypi
tensorflow-graphics       2021.12.3                pypi_0    pypi
tensorflow-io-gcs-filesystem 0.37.1                   pypi_0    pypi
tensorflow-metadata       1.17.2                   pypi_0    pypi
termcolor                 3.1.0                    pypi_0    pypi
timm                      0.9.10                   pypi_0    pypi
tk                        8.6.15               h54e0aa7_0  
tokenizers                0.19.1                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.3.0                    pypi_0    pypi
torch                     2.2.0                    pypi_0    pypi
torchaudio                2.2.0                    pypi_0    pypi
torchvision               0.17.0                   pypi_0    pypi
tqdm                      4.67.1                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
transformers              4.40.1                   pypi_0    pypi
trimesh                   4.8.3                    pypi_0    pypi
triton                    2.2.0                    pypi_0    pypi
typeguard                 2.13.3                   pypi_0    pypi
typing-extensions         4.15.0                   pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
typing-inspection         0.4.2                    pypi_0    pypi
tzdata                    2025b                h04d1e81_0  
urllib3                   2.5.0                    pypi_0    pypi
uvicorn                   0.38.0                   pypi_0    pypi
wandb                     0.22.2                   pypi_0    pypi
werkzeug                  3.1.3                    pypi_0    pypi
wheel                     0.45.1                   pypi_0    pypi
wrapt                     1.14.2                   pypi_0    pypi
xorg-libx11               1.8.12               h9b100fa_1  
xorg-libxau               1.0.12               h9b100fa_0  
xorg-libxdmcp             1.1.5                h9b100fa_0  
xorg-xorgproto            2024.1               h5eee18b_1  
xz                        5.6.4                h5eee18b_1  
zipp                      3.23.0                   pypi_0    pypi
zlib                      1.3.1                hb25bd0a_0 
```

**Comment by JuilieZ** [comment]
> I have the same problem, the reproduced results on LIBERO-Spatial is also exact 56.6% as reported by [@arashakb](https://github.com/arashakb) . I have tried installing mujoco==3.32 as suggested but the results are still bad (58.0%). FYI, I follow the instruction in [LIBERO](https://github.com/moojink/openvla-oft/blob/main/LIBERO.md#launching-libero-evaluations).md, where I download the HF's pretrained model and run the evaluation code without changing any part. I use one H100 for evaluation and my conda env is as follows:
> 
> ```
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main  
> _openmp_mutex             5.1                       1_gnu  
> absl-py                   2.3.1                    pypi_0    pypi
> accelerate                1.10.1                   pypi_0    pypi
> annotated-types           0.7.0                    pypi_0    pypi
> anyio                     4.11.0                   pypi_0    pypi
> array-record              0.8.1                    pypi_0    pypi
> astunparse                1.6.3                    pypi_0    pypi
> attrs                     25.4.0                   pypi_0    pypi
> bddl                      3.6.0                    pypi_0    pypi
> bzip2                     1.0.8                h5eee18b_6  
> ca-certificates           2025.9.9             h06a4308_0  
> cachetools                6.2.1                    pypi_0    pypi
> certifi                   2025.10.5                pypi_0    pypi
> charset-normalizer        3.4.4                    pypi_0    pypi
> click                     8.3.0                    pypi_0    pypi
> cloudpickle               3.1.1                    pypi_0    pypi
> contourpy                 1.3.2                    pypi_0    pypi
> cycler                    0.12.1                   pypi_0    pypi
> diffusers                 0.30.3                   pypi_0    pypi
> dlimp                     0.0.1                    pypi_0    pypi
> dm-tree                   0.1.9                    pypi_0    pypi
> draccus                   0.8.0                    pypi_0    pypi
> easydict                  1.13                     pypi_0    pypi
> einops                    0.8.1                    pypi_0    pypi
> etils                     1.13.0                   pypi_0    pypi
> evdev                     1.9.2                    pypi_0    pypi
> exceptiongroup            1.3.0                    pypi_0    pypi
> expat                     2.7.1                h6a678d5_0  
> fastapi                   0.119.1                  pypi_0    pypi
> fastjsonschema            2.21.2                   pypi_0    pypi
> filelock                  3.20.0                   pypi_0    pypi
> flatbuffers               25.9.23                  pypi_0    pypi
> fonttools                 4.60.1                   pypi_0    pypi
> fsspec                    2025.9.0                 pypi_0    pypi
> future                    1.0.0                    pypi_0    pypi
> gast                      0.6.0                    pypi_0    pypi
> gitdb                     4.0.12                   pypi_0    pypi
> gitpython                 3.1.45                   pypi_0    pypi
> glfw                      2.10.0                   pypi_0    pypi
> google-auth               2.41.1                   pypi_0    pypi
> google-auth-oauthlib      1.2.2                    pypi_0    pypi
> google-pasta              0.2.0                    pypi_0    pypi
> grpcio                    1.75.1                   pypi_0    pypi
> gym                       0.26.2                   pypi_0    pypi
> gym-notices               0.1.0                    pypi_0    pypi
> h11                       0.16.0                   pypi_0    pypi
> h5py                      3.15.1                   pypi_0    pypi
> hf-xet                    1.1.10                   pypi_0    pypi
> huggingface-hub           0.35.3                   pypi_0    pypi
> idna                      3.11                     pypi_0    pypi
> imageio                   2.37.0                   pypi_0    pypi
> imageio-ffmpeg            0.6.0                    pypi_0    pypi
> importlib-metadata        8.7.0                    pypi_0    pypi
> importlib-resources       6.5.2                    pypi_0    pypi
> iniconfig                 2.3.0                    pypi_0    pypi
> jinja2                    3.1.6                    pypi_0    pypi
> joblib                    1.5.2                    pypi_0    pypi
> json-numpy                2.1.1                    pypi_0    pypi
> jsonlines                 4.0.0                    pypi_0    pypi
> jsonschema                4.25.1                   pypi_0    pypi
> jsonschema-specifications 2025.9.1                 pypi_0    pypi
> jupyter-core              5.9.1                    pypi_0    pypi
> jupytext                  1.18.1                   pypi_0    pypi
> keras                     2.15.0                   pypi_0    pypi
> kiwisolver                1.4.9                    pypi_0    pypi
> ld_impl_linux-64          2.44                 h153f514_2  
> libclang                  18.1.1                   pypi_0    pypi
> libero                    0.1.0                    pypi_0    pypi
> libffi                    3.4.4                h6a678d5_1  
> libgcc-ng                 11.2.0               h1234567_1  
> libgomp                   11.2.0               h1234567_1  
> libstdcxx-ng              11.2.0               h1234567_1  
> libuuid                   1.41.5               h5eee18b_0  
> libxcb                    1.17.0               h9b100fa_0  
> libzlib                   1.3.1                hb25bd0a_0  
> llvmlite                  0.45.1                   pypi_0    pypi
> markdown                  3.9                      pypi_0    pypi
> markdown-it-py            4.0.0                    pypi_0    pypi
> markupsafe                3.0.3                    pypi_0    pypi
> matplotlib                3.10.7                   pypi_0    pypi
> mdit-py-plugins           0.5.0                    pypi_0    pypi
> mdurl                     0.1.2                    pypi_0    pypi
> mergedeep                 1.3.4                    pypi_0    pypi
> ml-dtypes                 0.2.0                    pypi_0    pypi
> mpmath                    1.3.0                    pypi_0    pypi
> mujoco                    3.3.2                    pypi_0    pypi
> mypy-extensions           1.1.0                    pypi_0    pypi
> nbformat                  5.10.4                   pypi_0    pypi
> ncurses                   6.5                  h7934f7d_0  
> networkx                  3.4.2                    pypi_0    pypi
> nltk                      3.9.2                    pypi_0    pypi
> numba                     0.62.1                   pypi_0    pypi
> numpy                     1.26.4                   pypi_0    pypi
> nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
> nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
> nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
> nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
> nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
> nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
> nvidia-cufile-cu12        1.13.1.3                 pypi_0    pypi
> nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
> nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
> nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
> nvidia-cusparselt-cu12    0.7.1                    pypi_0    pypi
> nvidia-nccl-cu12          2.19.3                   pypi_0    pypi
> nvidia-nvjitlink-cu12     12.8.93                  pypi_0    pypi
> nvidia-nvshmem-cu12       3.3.20                   pypi_0    pypi
> nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
> oauthlib                  3.3.1                    pypi_0    pypi
> opencv-python             4.12.0.88                pypi_0    pypi
> openexr                   3.4.2                    pypi_0    pypi
> openssl                   3.0.18               hd6dcaed_0  
> openvla-oft               0.0.1                    pypi_0    pypi
> opt-einsum                3.4.0                    pypi_0    pypi
> packaging                 25.0                     pypi_0    pypi
> peft                      0.11.1                   pypi_0    pypi
> pillow                    12.0.0                   pypi_0    pypi
> pip                       25.2               pyhc872135_1  
> platformdirs              4.5.0                    pypi_0    pypi
> pluggy                    1.6.0                    pypi_0    pypi
> promise                   2.3                      pypi_0    pypi
> protobuf                  4.21.12                  pypi_0    pypi
> psutil                    7.1.1                    pypi_0    pypi
> pthread-stubs             0.3                  h0ce48e5_1  
> pyasn1                    0.6.1                    pypi_0    pypi
> pyasn1-modules            0.4.2                    pypi_0    pypi
> pydantic                  2.12.3                   pypi_0    pypi
> pydantic-core             2.41.4                   pypi_0    pypi
> pygments                  2.19.2                   pypi_0    pypi
> pynput                    1.8.1                    pypi_0    pypi
> pyopengl                  3.1.10                   pypi_0    pypi
> pyparsing                 3.2.5                    pypi_0    pypi
> pytest                    8.4.2                    pypi_0    pypi
> python                    3.10.18              h1a3bd86_0  
> python-dateutil           2.9.0.post0              pypi_0    pypi
> python-xlib               0.33                     pypi_0    pypi
> pyyaml                    6.0.3                    pypi_0    pypi
> pyyaml-include            1.4.1                    pypi_0    pypi
> readline                  8.3                  hc2a1206_0  
> referencing               0.37.0                   pypi_0    pypi
> regex                     2025.9.18                pypi_0    pypi
> requests                  2.32.5                   pypi_0    pypi
> requests-oauthlib         2.0.0                    pypi_0    pypi
> rich                      14.2.0                   pypi_0    pypi
> robosuite                 1.4.1                    pypi_0    pypi
> rpds-py                   0.28.0                   pypi_0    pypi
> rsa                       4.9.1                    pypi_0    pypi
> safetensors               0.6.2                    pypi_0    pypi
> scipy                     1.15.3                   pypi_0    pypi
> sentencepiece             0.1.99                   pypi_0    pypi
> sentry-sdk                2.42.0                   pypi_0    pypi
> setuptools                80.9.0                   pypi_0    pypi
> six                       1.17.0                   pypi_0    pypi
> smmap                     5.0.2                    pypi_0    pypi
> sniffio                   1.3.1                    pypi_0    pypi
> sqlite                    3.50.2               hb25bd0a_1  
> starlette                 0.48.0                   pypi_0    pypi
> sympy                     1.14.0                   pypi_0    pypi
> tensorboard               2.15.2                   pypi_0    pypi
> tensorboard-data-server   0.7.2                    pypi_0    pypi
> tensorflow                2.15.0                   pypi_0    pypi
> tensorflow-addons         0.23.0                   pypi_0    pypi
> tensorflow-datasets       4.9.3                    pypi_0    pypi
> tensorflow-estimator      2.15.0                   pypi_0    pypi
> tensorflow-graphics       2021.12.3                pypi_0    pypi
> tensorflow-io-gcs-filesystem 0.37.1                   pypi_0    pypi
> tensorflow-metadata       1.17.2                   pypi_0    pypi
> termcolor                 3.1.0                    pypi_0    pypi
> timm                      0.9.10                   pypi_0    pypi
> tk                        8.6.15               h54e0aa7_0  
> tokenizers                0.19.1                   pypi_0    pypi
> toml                      0.10.2                   pypi_0    pypi
> tomli                     2.3.0                    pypi_0    pypi
> torch                     2.2.0                    pypi_0    pypi
> torchaudio                2.2.0                    pypi_0    pypi
> torchvision               0.17.0                   pypi_0    pypi
> tqdm                      4.67.1                   pypi_0    pypi
> traitlets                 5.14.3                   pypi_0    pypi
> transformers              4.40.1                   pypi_0    pypi
> trimesh                   4.8.3                    pypi_0    pypi
> triton                    2.2.0                    pypi_0    pypi
> typeguard                 2.13.3                   pypi_0    pypi
> typing-extensions         4.15.0                   pypi_0    pypi
> typing-inspect            0.9.0                    pypi_0    pypi
> typing-inspection         0.4.2                    pypi_0    pypi
> tzdata                    2025b                h04d1e81_0  
> urllib3                   2.5.0                    pypi_0    pypi
> uvicorn                   0.38.0                   pypi_0    pypi
> wandb                     0.22.2                   pypi_0    pypi
> werkzeug                  3.1.3                    pypi_0    pypi
> wheel                     0.45.1                   pypi_0    pypi
> wrapt                     1.14.2                   pypi_0    pypi
> xorg-libx11               1.8.12               h9b100fa_1  
> xorg-libxau               1.0.12               h9b100fa_0  
> xorg-libxdmcp             1.1.5                h9b100fa_0  
> xorg-xorgproto            2024.1               h5eee18b_1  
> xz                        5.6.4                h5eee18b_1  
> zipp                      3.23.0                   pypi_0    pypi
> zlib                      1.3.1                hb25bd0a_0 
> ```

have ur problem solved? I met the same problem,and it seem no real improvements even if I pip install mujoco==3.3.2
