### ISSUE TITLE
OOM when fine-tune libera dataset

### ISSUE THREAD

**Issue by xbkaishui** [moojink/openvla-oft#28]
Hello: 

I have issue when fine-tune libera dataset, my resource is 5* RTX4090 (24G),  error happens during save and load model 
 

> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 252.00 MiB. GPU 0 has a total capacity of 23.65 GiB of which 62.19 MiB is free. Including non-PyTorch memory, this process has 384.00 MiB memory in use. Process 2343934 has 636.00 MiB memory in use. Process 2343932 has 384.00 MiB memory in use. Process 2343931 has 384.00 MiB memory in use. Process 2343929 has 21.44 GiB memory in use. Process 2343933 has 384.00 MiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
^M                                                           ^MTraceback (most recent call last):
  File "/data/codes/openvla-oft/vla-scripts/finetune.py", line 1145, in <module>
    finetune()
  File "/root/miniconda3/envs/vla/lib/python3.10/site-packages/draccus/argparsing.py", line 203, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/data/codes/openvla-oft/vla-scripts/finetune.py", line 1106, in finetune
    save_training_checkpoint(
  File "/data/codes/openvla-oft/vla-scripts/finetune.py", line 659, in save_training_checkpoint
    merged_vla = PeftModel.from_pretrained(base_vla, adapter_dir)
  File "/root/miniconda3/envs/vla/lib/python3.10/site-packages/peft/peft_model.py", line 430, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/root/miniconda3/envs/vla/lib/python3.10/site-packages/peft/peft_model.py", line 984, in load_adapter
    adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
  File "/root/miniconda3/envs/vla/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 444, in load_peft_weights
    adapters_weights = safe_load_file(filename, device=device)
  File "/root/miniconda3/envs/vla/lib/python3.10/site-packages/safetensors/torch.py", line 315, in load_file
    result[k] = f.get_tensor(k)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 252.00 MiB. GPU 0 has a total capacity of 23.65 GiB of which 62.19 MiB is free. Process 2343930 has 384.00 MiB memory in use. Process 2343934 has 636.00 MiB memory in use. Process 2343932 has 384.00 MiB memory in use. Including non-PyTorch memory, this process has 384.00 MiB memory in use. Process 2343929 has 21.44 GiB memory in use. Process 2343933 has 384.00 MiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
^M                                                           ^MTraceback (most recent call last):
  File "/data/codes/openvla-oft/vla-scripts/finetune.py", line 1145, in <module>
    finetune()
  File "/root/miniconda3/envs/vla/lib/python3.10/site-packages/draccus/argparsing.py", line 203, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/data/codes/openvla-oft/vla-scripts/finetune.py", line 1106, in finetune
    save_training_checkpoint(
  File "/data/codes/openvla-oft/vla-scripts/finetune.py", line 659, in save_training_checkpoint
    merged_vla = PeftModel.from_pretrained(base_vla, adapter_dir)
  File "/root/miniconda3/envs/vla/lib/python3.10/site-packages/peft/peft_model.py", line 430, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/root/miniconda3/envs/vla/lib/python3.10/site-packages/peft/peft_model.py", line 984, in load_adapter
    adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
  File "/root/miniconda3/envs/vla/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 444, in load_peft_weights
    adapters_weights = safe_load_file(filename, device=device)
  File "/root/miniconda3/envs/vla/lib/python3.10/site-packages/safetensors/torch.py", line 315, in load_file
    result[k] = f.get_tensor(k)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 252.00 MiB. GPU 0 has a total capacity of 23.65 GiB of which 62.19 MiB is free. Process 2343930 has 384.00 MiB memory in use. Process 2343934 has 636.00 MiB memory in use. Process 2343932 has 384.00 MiB memory in
use. Process 2343931 has 384.00 MiB memory in use. Process 2343929 has 21.44 GiB memory in use. Including non-PyTorch memory, this process has 384.00 MiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If
 reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2025-03-28 16:13:42,075] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2343929 closing signal SIGTERM
[2025-03-28 16:13:42,078] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2343933 closing signal SIGTERM
[2025-03-28 16:13:42,079] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2343934 closing signal SIGTERM
[2025-03-28 16:13:43,754] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 2343930) of binary: /root/miniconda3/envs/vla/bin/python
Traceback (most recent call last):

**Comment by LukeLIN-web** [comment]
One 3rd image, bs=8,   requires 38GBvram.
24GB may cannot train it. 

 bfloat16  LIBERO - 1 input image (third-person camera), 7 action dimensions, action chunk size 8, batch size 1 → **25.6 GB** .   batch size 8 per GPU will require ~62 GB VRAM, and batch size 1 per GPU will require ~25 GB VRAM.

**Comment by zhan72** [comment]
change finetune.py  line 654 to 
```
base_vla = AutoModelForVision2Seq.from_pretrained(
            cfg.vla_path, torch_dtype=torch.bfloat16, low_cpu_mem_usage=True, trust_remote_code=True, device_map="cpu"
        )
```
It works for me!

**Comment by xbkaishui** [comment]
OK let me try， why move to cpu device ?

**Comment by moojink** [comment]
Thank you @zhan72 for that suggestion.

Alternatively, you can set `--merge_lora_during_training` to `False` and do the LoRA adapter merging entirely offline using [`vla-scripts/merge_lora_weights_and_save.py`](https://github.com/moojink/openvla-oft/blob/main/vla-scripts/merge_lora_weights_and_save.py). This is what I do in my own workflow since I don't end up using all the checkpoints anyway.
