### ISSUE TITLE
Running out of GPU space when inferencing model using LoRA finetuned model

### ISSUE THREAD

**Issue by dean4ta** [moojink/openvla-oft#6]
After finetuning the base model using [Fine-Tuning on ALOHA Robot Data](https://github.com/moojink/openvla-oft/blob/main/ALOHA.md#fine-tuning-on-aloha-robot-data), I then merged the LoRA adapter into the base model using [merge_lora_weights_and_save.py](https://github.com/moojink/openvla-oft/blob/main/vla-scripts/merge_lora_weights_and_save.py).

The model was finetuned on 4 H100s.

I am facing memory errors when loading the model onto my server which is running a RTX4090 (24GB).

Command for launching model on server:
```
python vla-scripts/deploy.py --pretrained_checkpoint /home/dean/Models/openvla-7b+aloha1_taskbox_800_demos+b4+lr-0.0005+lora-r32+dropout-0.0--image_aug--100000_chkpt_merged/ --use_l1_regression True --use_film True --num_images_in_input 3 --use_proprio True --center_crop True --num_open_loop_steps 25 --unnorm_key aloha1_taskbox_800_demos
```

terminal output:
```log
Using ALOHA constants:
  NUM_ACTIONS_CHUNK = 25
  ACTION_DIM = 14
  PROPRIO_DIM = 14
  ACTION_PROPRIO_NORMALIZATION_TYPE = bounds
If needed, manually set the correct constants in `prismatic/vla/constants.py`!
Instantiating pretrained VLA policy...
Created backup of original config at: /home/dean/Models/openvla-7b+aloha1_taskbox_800_demos+b4+lr-0.0005+lora-r32+dropout-0.0--image_aug--100000_chkpt_merged/config.json.back.20250305_132636
Updated config.json at: /home/dean/Models/openvla-7b+aloha1_taskbox_800_demos+b4+lr-0.0005+lora-r32+dropout-0.0--image_aug--100000_chkpt_merged/config.json
Changes made:
  - Set AutoConfig to "configuration_prismatic.OpenVLAConfig"
  - Set AutoModelForVision2Seq to "modeling_prismatic.OpenVLAForActionPrediction"
03/05 [13:28:27] ERROR    | >> Traceback (most recent call last):                                             deploy.py:102
                            File "/home/dean/Code/openVLA/openvla-oft/vla-scripts/deploy.py", line 93, in                  
                          get_server_action                                                                                
                              action = get_vla_action(                                                                     
                            File "/home/dean/Code/openVLA/openvla-oft/experiments/robot/openvla_utils.py",                 
                          line 780, in get_vla_action                                                                      
                              action, _ = vla.predict_action(                                                              
                            File                                                                                           
                          "/home/dean/.cache/huggingface/modules/transformers_modules/modeling_prismatic.py",              
                          line 1046, in predict_action                                                                     
                              normalized_actions, actions_hidden_states =                                                  
                          self._regression_or_discrete_prediction(                                                         
                            File                                                                                           
                          "/home/dean/.cache/huggingface/modules/transformers_modules/modeling_prismatic.py",              
                          line 901, in _regression_or_discrete_prediction                                                  
                              language_model_output = self.language_model(                                                 
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/nn/modul              
                          es/module.py", line 1511, in _wrapped_call_impl                                                  
                              return self._call_impl(*args, **kwargs)                                                      
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/nn/modul              
                          es/module.py", line 1520, in _call_impl                                                          
                              return forward_call(*args, **kwargs)                                                         
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/transformers/m              
                          odels/llama/modeling_llama.py", line 1262, in forward                                            
                              outputs = self.model(                                                                        
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/nn/modul              
                          es/module.py", line 1511, in _wrapped_call_impl                                                  
                              return self._call_impl(*args, **kwargs)                                                      
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/nn/modul              
                          es/module.py", line 1520, in _call_impl                                                          
                              return forward_call(*args, **kwargs)                                                         
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/transformers/m              
                          odels/llama/modeling_llama.py", line 1072, in forward                                            
                              layer_outputs = decoder_layer(                                                               
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/nn/modul              
                          es/module.py", line 1511, in _wrapped_call_impl                                                  
                              return self._call_impl(*args, **kwargs)                                                      
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/nn/modul              
                          es/module.py", line 1520, in _call_impl                                                          
                              return forward_call(*args, **kwargs)                                                         
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/transformers/m              
                          odels/llama/modeling_llama.py", line 795, in forward                                             
                              hidden_states, self_attn_weights, present_key_value = self.self_attn(                        
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/nn/modul              
                          es/module.py", line 1511, in _wrapped_call_impl                                                  
                              return self._call_impl(*args, **kwargs)                                                      
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/nn/modul              
                          es/module.py", line 1520, in _call_impl                                                          
                              return forward_call(*args, **kwargs)                                                         
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/transformers/m              
                          odels/llama/modeling_llama.py", line 638, in forward                                             
                              value_states = self.v_proj(hidden_states)                                                    
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/nn/modul              
                          es/module.py", line 1511, in _wrapped_call_impl                                                  
                              return self._call_impl(*args, **kwargs)                                                      
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/nn/modul              
                          es/module.py", line 1520, in _call_impl                                                          
                              return forward_call(*args, **kwargs)                                                         
                            File                                                                                           
                          "/home/dean/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/peft/tuners/lo              
                          ra/layer.py", line 569, in forward                                                               
                              result = result + lora_B(lora_A(dropout(x))) * scaling                                       
                          torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0              
                          has a total capacity of 23.55 GiB of which 17.06 MiB is free. Including non-PyTorch              
                          memory, this process has 23.49 GiB memory in use. Of the allocated memory 23.01 GiB              
                          is allocated by PyTorch, and 11.90 MiB is reserved by PyTorch but unallocated. If                
                          reserved but unallocated memory is large try setting                                             
                          PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See                    
                          documentation for Memory Management                                                              
                          (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)                          
                                                                                                                           
                 WARNING  | >> Your request threw an error; make sure your request complies with the expected deploy.py:103
                          format:                                                                                          
                          {'observation': dict, 'instruction': str}                                                        
                                                                                                                           
INFO:     10.137.70.35:42758 - "POST /act HTTP/1.1" 200 OK

```

## Things I have tried...
 - I ran the model on an A6000 machine and I was able to inference the model. I am seeing about 25 GB of usage of the 46 GB available. (25 GB is so close to fitting on the RTX4090 🤏)
 - I am able to launch the model if I set `use_film` to false, but we have a few different tasks we collected data on and would like to inference after loading.
 - I verified the `{'observation': dict, 'instruction': str}` are valid
 - I tried to load in `load_in_8bit` mode but the model was not trained that way

Is there anything I can do to try to make the model fit?

Thanks,
Dean

**Comment by moojink** [comment]
Hi @dean4ta, thank you for providing all these details! We just pushed a [commit](https://github.com/moojink/openvla-oft/commit/0b75f6f77d4716ba7e4701b5b0e94dd10baa236f) that reduces the GPU memory usage at test time. The issue was that gradient tracking was enabled during inference; we disabled it by adding `with torch.inference_mode():` to the `get_vla_action()` function in `openvla_utils.py`, and now ALOHA inference only requires ~18.0 GB VRAM.

If you would like to analyze the peak GPU memory utilization during ALOHA inference, you can add this line after the `get_vla_action()` function call in the `OpenVLAServer.get_server_action()` function in `deploy.py`:

```
print(f"Max GPU memory allocated so far: {torch.cuda.max_memory_allocated() / 10**9 : .3f} GB")
```

On my end, while doing the task `scoop raisins into bowl`, I observe the following:

```
Max GPU memory allocated so far:  18.033 GB
```

Hope that helps, and thank you for bringing this to our attention!

-Moo Jin

**Comment by dean4ta** [comment]
Hi @moojink , I just tried running the server on the RTX4090 and I am having success. I am also getting around 18 GBs as well.

Thanks for the solution!
Dean

**Comment by moojink** [comment]
@dean4ta Great to hear! Thank you for letting me know!

**Comment by moojink** [comment]
Hi @dean4ta, we pushed another [commit](https://github.com/moojink/openvla-oft/commit/d8bf4996d6a7a05f1320a2a6f1e7a3e90e1cd38d) that sets the ALOHA control frequency to 25 Hz (instead of the default 50 Hz). We meant to check this in earlier but missed it because the client side code we used for evaluations was on a different machine that had some uncommitted ALOHA eval code.

Just wanted to let you know in case you are using our exact ALOHA client code for evaluations!
